name: Schedule Test

on:
  schedule:
    - cron: "13,28,43,58 * * * *"
      timezone: "Asia/Seoul"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule test
        run: |
          echo "Scheduled workflow is working"
          date
